package snd.komelia.ui.icons.mangabaka.flags

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import snd.komelia.ui.icons.AppIcons

val AppIcons.FlagBr: ImageVector
    get() {
        if (_FlagBr != null) {
            return _FlagBr!!
        }
        _FlagBr = ImageVector.Builder(
            name = "FlagBr",
            defaultWidth = 640.dp,
            defaultHeight = 480.dp,
            viewportWidth = 640f,
            viewportHeight = 480f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF229E45)),
                pathFillType = PathFillType.EvenOdd
            ) {
                moveTo(0f, 0f)
                horizontalLineToRelative(640f)
                verticalLineToRelative(480f)
                horizontalLineTo(0f)
                close()
            }
            path(
                fill = SolidColor(Color(0xFFF8E509)),
                pathFillType = PathFillType.EvenOdd
            ) {
                moveToRelative(321.4f, 436f)
                lineToRelative(301.5f, -195.7f)
                lineTo(319.6f, 44f)
                lineTo(17.1f, 240.7f)
                close()
            }
            path(
                fill = SolidColor(Color(0xFF2B49A3)),
                pathFillType = PathFillType.EvenOdd
            ) {
                moveTo(452.8f, 240f)
                curveToRelative(0f, 70.3f, -57.1f, 127.3f, -127.6f, 127.3f)
                arcTo(127.4f, 127.4f, 0f, isMoreThanHalf = true, isPositiveArc = true, 452.8f, 240f)
            }
            path(
                fill = SolidColor(Color(0xFFFFFFEF)),
                pathFillType = PathFillType.EvenOdd
            ) {
                moveToRelative(283.3f, 316.3f)
                lineToRelative(-4f, -2.3f)
                lineToRelative(-4f, 2f)
                lineToRelative(0.9f, -4.5f)
                lineToRelative(-3.2f, -3.4f)
                lineToRelative(4.5f, -0.5f)
                lineToRelative(2.2f, -4f)
                lineToRelative(1.9f, 4.2f)
                lineToRelative(4.4f, 0.8f)
                lineToRelative(-3.3f, 3f)
                moveToRelative(86f, 26.3f)
                lineToRelative(-3.9f, -2.3f)
                lineToRelative(-4f, 2f)
                lineToRelative(0.8f, -4.5f)
                lineToRelative(-3.1f, -3.3f)
                lineToRelative(4.5f, -0.5f)
                lineToRelative(2.1f, -4.1f)
                lineToRelative(2f, 4.2f)
                lineToRelative(4.4f, 0.8f)
                lineToRelative(-3.4f, 3.1f)
                moveToRelative(-36.2f, -30f)
                lineToRelative(-3.4f, -2f)
                lineToRelative(-3.5f, 1.8f)
                lineToRelative(0.8f, -3.9f)
                lineToRelative(-2.8f, -2.9f)
                lineToRelative(4f, -0.4f)
                lineToRelative(1.8f, -3.6f)
                lineToRelative(1.6f, 3.7f)
                lineToRelative(3.9f, 0.7f)
                lineToRelative(-3f, 2.7f)
                moveToRelative(87f, -8.5f)
                lineToRelative(-3.4f, -2f)
                lineToRelative(-3.5f, 1.8f)
                lineToRelative(0.8f, -3.9f)
                lineToRelative(-2.7f, -2.8f)
                lineToRelative(3.9f, -0.4f)
                lineToRelative(1.8f, -3.5f)
                lineToRelative(1.6f, 3.6f)
                lineToRelative(3.8f, 0.7f)
                lineToRelative(-2.9f, 2.6f)
                moveToRelative(-87.3f, -22f)
                lineToRelative(-4f, -2.2f)
                lineToRelative(-4f, 2f)
                lineToRelative(0.8f, -4.6f)
                lineToRelative(-3.1f, -3.3f)
                lineToRelative(4.5f, -0.5f)
                lineToRelative(2.1f, -4.1f)
                lineToRelative(2f, 4.2f)
                lineToRelative(4.4f, 0.8f)
                lineToRelative(-3.4f, 3.2f)
                moveToRelative(-104.6f, -35f)
                lineToRelative(-4f, -2.2f)
                lineToRelative(-4f, 2f)
                lineToRelative(1f, -4.6f)
                lineToRelative(-3.3f, -3.3f)
                lineToRelative(4.6f, -0.5f)
                lineToRelative(2f, -4.1f)
                lineToRelative(2f, 4.2f)
                lineToRelative(4.4f, 0.8f)
                lineToRelative(-3.3f, 3.1f)
                moveToRelative(13.3f, 57.2f)
                lineToRelative(-4f, -2.3f)
                lineToRelative(-4f, 2f)
                lineToRelative(0.9f, -4.5f)
                lineToRelative(-3.2f, -3.3f)
                lineToRelative(4.5f, -0.6f)
                lineToRelative(2.1f, -4f)
                lineToRelative(2f, 4.2f)
                lineToRelative(4.4f, 0.8f)
                lineToRelative(-3.3f, 3.1f)
                moveToRelative(132f, -67.3f)
                lineToRelative(-3.6f, -2f)
                lineToRelative(-3.6f, 1.8f)
                lineToRelative(0.8f, -4f)
                lineToRelative(-2.8f, -3f)
                lineToRelative(4f, -0.5f)
                lineToRelative(1.9f, -3.6f)
                lineToRelative(1.7f, 3.8f)
                lineToRelative(4f, 0.7f)
                lineToRelative(-3f, 2.7f)
                moveToRelative(-6.7f, 38.3f)
                lineToRelative(-2.7f, -1.6f)
                lineToRelative(-2.9f, 1.4f)
                lineToRelative(0.6f, -3.2f)
                lineToRelative(-2.2f, -2.3f)
                lineToRelative(3.2f, -0.4f)
                lineToRelative(1.5f, -2.8f)
                lineToRelative(1.3f, 3f)
                lineToRelative(3f, 0.5f)
                lineToRelative(-2.2f, 2.2f)
                moveToRelative(-142.2f, 50.4f)
                lineToRelative(-2.7f, -1.5f)
                lineToRelative(-2.7f, 1.3f)
                lineToRelative(0.6f, -3f)
                lineToRelative(-2.1f, -2.2f)
                lineToRelative(3f, -0.4f)
                lineToRelative(1.4f, -2.7f)
                lineToRelative(1.3f, 2.8f)
                lineToRelative(3f, 0.6f)
                lineToRelative(-2.3f, 2f)
                moveTo(419f, 299.8f)
                lineToRelative(-2.2f, -1.1f)
                lineToRelative(-2.2f, 1f)
                lineToRelative(0.5f, -2.3f)
                lineToRelative(-1.7f, -1.6f)
                lineToRelative(2.4f, -0.3f)
                lineToRelative(1.2f, -2f)
                lineToRelative(1f, 2f)
                lineToRelative(2.5f, 0.5f)
                lineToRelative(-1.9f, 1.5f)
            }
            path(
                fill = SolidColor(Color(0xFFFFFFEF)),
                pathFillType = PathFillType.EvenOdd
            ) {
                moveToRelative(219.3f, 287.6f)
                lineToRelative(-2.7f, -1.5f)
                lineToRelative(-2.7f, 1.3f)
                lineToRelative(0.6f, -3f)
                lineToRelative(-2.1f, -2.2f)
                lineToRelative(3f, -0.4f)
                lineToRelative(1.4f, -2.7f)
                lineToRelative(1.3f, 2.8f)
                lineToRelative(3f, 0.6f)
                lineToRelative(-2.3f, 2f)
            }
            path(
                fill = SolidColor(Color(0xFFFFFFEF)),
                pathFillType = PathFillType.EvenOdd
            ) {
                moveToRelative(219.3f, 287.6f)
                lineToRelative(-2.7f, -1.5f)
                lineToRelative(-2.7f, 1.3f)
                lineToRelative(0.6f, -3f)
                lineToRelative(-2.1f, -2.2f)
                lineToRelative(3f, -0.4f)
                lineToRelative(1.4f, -2.7f)
                lineToRelative(1.3f, 2.8f)
                lineToRelative(3f, 0.6f)
                lineToRelative(-2.3f, 2f)
                moveToRelative(42.3f, 3f)
                lineToRelative(-2.6f, -1.4f)
                lineToRelative(-2.7f, 1.3f)
                lineToRelative(0.6f, -3f)
                lineToRelative(-2.1f, -2.2f)
                lineToRelative(3f, -0.4f)
                lineToRelative(1.4f, -2.7f)
                lineToRelative(1.3f, 2.8f)
                lineToRelative(3f, 0.5f)
                lineToRelative(-2.3f, 2.1f)
                moveToRelative(-4.8f, 17f)
                lineToRelative(-2.6f, -1.5f)
                lineToRelative(-2.7f, 1.4f)
                lineToRelative(0.6f, -3f)
                lineToRelative(-2.1f, -2.3f)
                lineToRelative(3f, -0.4f)
                lineToRelative(1.4f, -2.7f)
                lineToRelative(1.3f, 2.8f)
                lineToRelative(3f, 0.6f)
                lineToRelative(-2.3f, 2f)
                moveToRelative(87.4f, -22.2f)
                lineToRelative(-2.6f, -1.6f)
                lineToRelative(-2.8f, 1.4f)
                lineToRelative(0.6f, -3f)
                lineToRelative(-2f, -2.3f)
                lineToRelative(3f, -0.3f)
                lineToRelative(1.4f, -2.7f)
                lineToRelative(1.2f, 2.8f)
                lineToRelative(3f, 0.5f)
                lineToRelative(-2.2f, 2.1f)
                moveToRelative(-25.1f, 3f)
                lineToRelative(-2.7f, -1.5f)
                lineToRelative(-2.7f, 1.4f)
                lineToRelative(0.6f, -3f)
                lineToRelative(-2f, -2.3f)
                lineToRelative(3f, -0.3f)
                lineToRelative(1.4f, -2.8f)
                lineToRelative(1.2f, 2.9f)
                lineToRelative(3f, 0.5f)
                lineToRelative(-2.2f, 2.1f)
                moveToRelative(-68.8f, -5.8f)
                lineToRelative(-1.7f, -1f)
                lineToRelative(-1.7f, 0.8f)
                lineToRelative(0.4f, -1.9f)
                lineToRelative(-1.3f, -1.4f)
                lineToRelative(1.9f, -0.2f)
                lineToRelative(0.8f, -1.7f)
                lineToRelative(0.8f, 1.8f)
                lineToRelative(1.9f, 0.3f)
                lineToRelative(-1.4f, 1.3f)
                moveToRelative(167.8f, 45.4f)
                lineToRelative(-2.6f, -1.5f)
                lineToRelative(-2.7f, 1.4f)
                lineToRelative(0.6f, -3f)
                lineToRelative(-2.1f, -2.3f)
                lineToRelative(3f, -0.4f)
                lineToRelative(1.4f, -2.7f)
                lineToRelative(1.3f, 2.8f)
                lineToRelative(3f, 0.6f)
                lineToRelative(-2.3f, 2f)
                moveToRelative(-20.8f, 6f)
                lineToRelative(-2.2f, -1.4f)
                lineToRelative(-2.3f, 1.2f)
                lineToRelative(0.5f, -2.6f)
                lineToRelative(-1.7f, -1.8f)
                lineToRelative(2.5f, -0.3f)
                lineToRelative(1.2f, -2.3f)
                lineToRelative(1f, 2.4f)
                lineToRelative(2.5f, 0.4f)
                lineToRelative(-1.9f, 1.8f)
                moveToRelative(10.4f, 2.3f)
                lineToRelative(-2f, -1.2f)
                lineToRelative(-2.1f, 1f)
                lineToRelative(0.4f, -2.3f)
                lineToRelative(-1.6f, -1.7f)
                lineToRelative(2.3f, -0.3f)
                lineToRelative(1.1f, -2f)
                lineToRelative(1f, 2f)
                lineToRelative(2.3f, 0.5f)
                lineToRelative(-1.7f, 1.6f)
                moveToRelative(29.1f, -22.8f)
                lineToRelative(-2f, -1f)
                lineToRelative(-2f, 1f)
                lineToRelative(0.5f, -2.3f)
                lineToRelative(-1.6f, -1.7f)
                lineToRelative(2.3f, -0.3f)
                lineToRelative(1f, -2f)
                lineToRelative(1f, 2.1f)
                lineToRelative(2.1f, 0.4f)
                lineToRelative(-1.6f, 1.6f)
                moveToRelative(-38.8f, 41.8f)
                lineToRelative(-2.5f, -1.4f)
                lineToRelative(-2.7f, 1.2f)
                lineToRelative(0.6f, -2.8f)
                lineToRelative(-2f, -2f)
                lineToRelative(3f, -0.3f)
                lineToRelative(1.3f, -2.5f)
                lineToRelative(1.2f, 2.6f)
                lineToRelative(3f, 0.5f)
                lineToRelative(-2.3f, 1.9f)
                moveToRelative(0.6f, 14.2f)
                lineToRelative(-2.4f, -1.4f)
                lineToRelative(-2.4f, 1.3f)
                lineToRelative(0.6f, -2.8f)
                lineToRelative(-1.9f, -2f)
                lineToRelative(2.7f, -0.4f)
                lineToRelative(1.2f, -2.5f)
                lineToRelative(1.1f, 2.6f)
                lineToRelative(2.7f, 0.5f)
                lineToRelative(-2f, 2f)
                moveToRelative(-19f, -23.1f)
                lineToRelative(-1.9f, -1.2f)
                lineToRelative(-2f, 1f)
                lineToRelative(0.4f, -2.2f)
                lineToRelative(-1.5f, -1.7f)
                lineToRelative(2.2f, -0.2f)
                lineToRelative(1f, -2f)
                lineToRelative(1f, 2f)
                lineToRelative(2.2f, 0.4f)
                lineToRelative(-1.6f, 1.6f)
                moveToRelative(-17.8f, 2.3f)
                lineToRelative(-2f, -1.2f)
                lineToRelative(-2f, 1f)
                lineToRelative(0.5f, -2.2f)
                lineToRelative(-1.6f, -1.7f)
                lineToRelative(2.3f, -0.2f)
                lineToRelative(1f, -2f)
                lineToRelative(1f, 2f)
                lineToRelative(2.1f, 0.4f)
                lineToRelative(-1.6f, 1.6f)
                moveToRelative(-30.4f, -24.6f)
                lineToRelative(-2f, -1.1f)
                lineToRelative(-2f, 1f)
                lineToRelative(0.5f, -2.3f)
                lineToRelative(-1.6f, -1.6f)
                lineToRelative(2.2f, -0.3f)
                lineToRelative(1f, -2f)
                lineToRelative(1f, 2f)
                lineToRelative(2.2f, 0.5f)
                lineToRelative(-1.6f, 1.5f)
                moveToRelative(3.7f, 57f)
                lineToRelative(-1.6f, -0.9f)
                lineToRelative(-1.8f, 0.9f)
                lineToRelative(0.4f, -2f)
                lineToRelative(-1.3f, -1.4f)
                lineToRelative(1.9f, -0.2f)
                lineToRelative(0.9f, -1.7f)
                lineToRelative(0.8f, 1.8f)
                lineToRelative(1.9f, 0.3f)
                lineToRelative(-1.4f, 1.3f)
                moveToRelative(-46.2f, -86.6f)
                lineToRelative(-4f, -2.3f)
                lineToRelative(-4f, 2f)
                lineToRelative(0.9f, -4.5f)
                lineToRelative(-3.2f, -3.3f)
                lineToRelative(4.5f, -0.6f)
                lineToRelative(2.2f, -4f)
                lineToRelative(1.9f, 4.2f)
                lineToRelative(4.4f, 0.8f)
                lineToRelative(-3.3f, 3.1f)
            }
            path(
                fill = SolidColor(Color.White),
                pathFillType = PathFillType.EvenOdd
            ) {
                moveTo(444.4f, 285.8f)
                arcToRelative(125f, 125f, 0f, isMoreThanHalf = false, isPositiveArc = false, 5.8f, -19.8f)
                curveToRelative(-67.8f, -59.5f, -143.3f, -90f, -238.7f, -83.7f)
                arcToRelative(125f, 125f, 0f, isMoreThanHalf = false, isPositiveArc = false, -8.5f, 20.9f)
                curveToRelative(113f, -10.8f, 196f, 39.2f, 241.4f, 82.6f)
            }
            path(fill = SolidColor(Color(0xFF309E3A))) {
                moveToRelative(414f, 252.4f)
                lineToRelative(2.3f, 1.3f)
                arcToRelative(3f, 3f, 0f, isMoreThanHalf = false, isPositiveArc = false, -0.3f, 2.2f)
                arcToRelative(3f, 3f, 0f, isMoreThanHalf = false, isPositiveArc = false, 1.4f, 1.7f)
                quadToRelative(1f, 0.8f, 2f, 0.7f)
                quadToRelative(0.9f, 0f, 1.3f, -0.7f)
                lineToRelative(0.2f, -0.9f)
                lineToRelative(-0.5f, -1f)
                lineToRelative(-1.5f, -1.8f)
                arcToRelative(8f, 8f, 0f, isMoreThanHalf = false, isPositiveArc = true, -1.8f, -3f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = true, 2f, -4.4f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = true, 2.3f, -0.2f)
                arcToRelative(7f, 7f, 0f, isMoreThanHalf = false, isPositiveArc = true, 2.6f, 1.2f)
                quadToRelative(2.1f, 1.5f, 2.6f, 3.2f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = true, -0.6f, 3.3f)
                lineToRelative(-2.4f, -1.5f)
                quadToRelative(0.5f, -1f, 0.2f, -1.7f)
                quadToRelative(-0.2f, -0.8f, -1.2f, -1.4f)
                arcToRelative(3f, 3f, 0f, isMoreThanHalf = false, isPositiveArc = false, -1.8f, -0.7f)
                arcToRelative(1f, 1f, 0f, isMoreThanHalf = false, isPositiveArc = false, -0.9f, 0.5f)
                quadToRelative(-0.3f, 0.4f, -0.1f, 1f)
                quadToRelative(0.2f, 0.8f, 1.6f, 2.2f)
                reflectiveQuadToRelative(2f, 2.5f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = true, -0.3f, 4.2f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = true, -1.9f, 1.5f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = true, -2.4f, 0.3f)
                quadToRelative(-1.3f, -0.3f, -2.8f, -1.3f)
                quadToRelative(-2.2f, -1.5f, -2.7f, -3.3f)
                arcToRelative(5f, 5f, 0f, isMoreThanHalf = false, isPositiveArc = true, 0.6f, -4f)
                close()
                moveTo(402.4f, 244.8f)
                lineTo(404.9f, 246.1f)
                arcToRelative(3f, 3f, 0f, isMoreThanHalf = false, isPositiveArc = false, -0.2f, 2.2f)
                arcToRelative(3f, 3f, 0f, isMoreThanHalf = false, isPositiveArc = false, 1.4f, 1.6f)
                quadToRelative(1.1f, 0.8f, 2f, 0.6f)
                quadToRelative(0.9f, 0f, 1.3f, -0.8f)
                lineToRelative(0.2f, -0.8f)
                quadToRelative(0f, -0.5f, -0.5f, -1f)
                lineToRelative(-1.6f, -1.8f)
                quadToRelative(-1.7f, -1.6f, -2f, -2.8f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = true, 0.4f, -3.1f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = true, 1.6f, -1.4f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = true, 2.2f, -0.3f)
                arcToRelative(7f, 7f, 0f, isMoreThanHalf = false, isPositiveArc = true, 2.6f, 1f)
                quadToRelative(2.3f, 1.5f, 2.7f, 3.1f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = true, -0.4f, 3.4f)
                lineToRelative(-2.5f, -1.4f)
                quadToRelative(0.5f, -1f, 0.2f, -1.7f)
                quadToRelative(-0.4f, -1f, -1.3f, -1.4f)
                arcToRelative(3f, 3f, 0f, isMoreThanHalf = false, isPositiveArc = false, -1.9f, -0.6f)
                arcToRelative(1f, 1f, 0f, isMoreThanHalf = false, isPositiveArc = false, -0.8f, 0.5f)
                quadToRelative(-0.3f, 0.4f, -0.1f, 1f)
                quadToRelative(0.3f, 0.8f, 1.7f, 2.2f)
                quadToRelative(1.5f, 1.5f, 2f, 2.4f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = true, 0f, 4.2f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = true, -1.8f, 1.6f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = true, -2.4f, 0.3f)
                arcToRelative(8f, 8f, 0f, isMoreThanHalf = false, isPositiveArc = true, -2.9f, -1.1f)
                arcToRelative(6f, 6f, 0f, isMoreThanHalf = false, isPositiveArc = true, -2.8f, -3.2f)
                arcToRelative(5f, 5f, 0f, isMoreThanHalf = false, isPositiveArc = true, 0.4f, -4f)
                moveToRelative(-14.2f, -3.8f)
                lineToRelative(7.3f, -12f)
                lineToRelative(8.8f, 5.5f)
                lineToRelative(-1.2f, 2f)
                lineToRelative(-6.4f, -4f)
                lineToRelative(-1.6f, 2.7f)
                lineToRelative(6f, 3.7f)
                lineToRelative(-1.3f, 2f)
                lineToRelative(-6f, -3.7f)
                lineToRelative(-2f, 3.3f)
                lineToRelative(6.7f, 4f)
                lineToRelative(-1.2f, 2f)
                close()
                moveTo(367.5f, 224f)
                lineTo(368.6f, 222f)
                lineTo(374f, 224.7f)
                lineTo(371.5f, 229.7f)
                quadToRelative(-1.2f, 0.3f, -3f, 0.2f)
                arcToRelative(9f, 9f, 0f, isMoreThanHalf = false, isPositiveArc = true, -3.3f, -1f)
                arcToRelative(8f, 8f, 0f, isMoreThanHalf = false, isPositiveArc = true, -3f, -2.6f)
                arcToRelative(6f, 6f, 0f, isMoreThanHalf = false, isPositiveArc = true, -1f, -3.5f)
                arcToRelative(9f, 9f, 0f, isMoreThanHalf = false, isPositiveArc = true, 1f, -3.7f)
                arcToRelative(8f, 8f, 0f, isMoreThanHalf = false, isPositiveArc = true, 2.6f, -3f)
                arcToRelative(6f, 6f, 0f, isMoreThanHalf = false, isPositiveArc = true, 3.6f, -1.1f)
                quadToRelative(1.4f, 0f, 3.2f, 1f)
                quadToRelative(2.4f, 1.1f, 3.1f, 2.8f)
                arcToRelative(5f, 5f, 0f, isMoreThanHalf = false, isPositiveArc = true, 0.3f, 3.5f)
                lineToRelative(-2.7f, -0.8f)
                arcToRelative(3f, 3f, 0f, isMoreThanHalf = false, isPositiveArc = false, -0.2f, -2f)
                quadToRelative(-0.4f, -0.9f, -1.6f, -1.4f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = false, -3.1f, -0.3f)
                quadToRelative(-1.5f, 0.5f, -2.6f, 2.6f)
                reflectiveQuadToRelative(-0.7f, 3.8f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = false, 2f, 2.4f)
                quadToRelative(0.8f, 0.5f, 1.7f, 0.5f)
                horizontalLineToRelative(1.8f)
                lineToRelative(0.8f, -1.6f)
                close()
                moveTo(277.3f, 201.7f)
                lineTo(279.3f, 187.7f)
                lineTo(283.5f, 188.4f)
                lineTo(284.6f, 198.2f)
                lineTo(288.5f, 189.2f)
                lineTo(292.7f, 189.8f)
                lineTo(290.7f, 203.6f)
                lineTo(288f, 203.2f)
                lineTo(289.7f, 192.3f)
                lineTo(285.3f, 202.8f)
                lineTo(282.6f, 202.4f)
                lineTo(281.5f, 191.1f)
                lineTo(279.9f, 202.1f)
                close()
                moveTo(263.2f, 200f)
                lineTo(264.5f, 186f)
                lineTo(274.8f, 187f)
                lineTo(274.6f, 189.4f)
                lineTo(267.1f, 188.7f)
                lineTo(266.8f, 191.7f)
                lineTo(273.8f, 192.4f)
                lineTo(273.5f, 194.8f)
                lineTo(266.5f, 194.1f)
                lineTo(266.2f, 197.9f)
                lineTo(274f, 198.6f)
                lineTo(273.8f, 201f)
                close()
            }
            path(
                fill = SolidColor(Color(0xFF309E3A)),
                strokeAlpha = 0.5f
            ) {
                moveTo(216.5f, 191.3f)
                quadToRelative(0f, -2.2f, 0.7f, -3.6f)
                arcToRelative(7f, 7f, 0f, isMoreThanHalf = false, isPositiveArc = true, 1.4f, -1.9f)
                arcToRelative(5f, 5f, 0f, isMoreThanHalf = false, isPositiveArc = true, 1.8f, -1.2f)
                quadToRelative(1.5f, -0.5f, 3f, -0.5f)
                quadToRelative(3.1f, 0.1f, 5f, 2f)
                arcToRelative(7f, 7f, 0f, isMoreThanHalf = false, isPositiveArc = true, 1.6f, 5.5f)
                quadToRelative(0f, 3.3f, -2f, 5.3f)
                arcToRelative(7f, 7f, 0f, isMoreThanHalf = false, isPositiveArc = true, -5f, 1.7f)
                arcToRelative(7f, 7f, 0f, isMoreThanHalf = false, isPositiveArc = true, -4.8f, -2f)
                arcToRelative(7f, 7f, 0f, isMoreThanHalf = false, isPositiveArc = true, -1.7f, -5.3f)
            }
            path(
                fill = SolidColor(Color(0xFFF7FFFF)),
                strokeAlpha = 0.5f
            ) {
                moveTo(219.4f, 191.3f)
                quadToRelative(0f, 2.3f, 1f, 3.6f)
                reflectiveQuadToRelative(2.8f, 1.3f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = false, 2.8f, -1.1f)
                quadToRelative(1f, -1.2f, 1.1f, -3.7f)
                quadToRelative(0.1f, -2.4f, -1f, -3.6f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = false, -2.7f, -1.3f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = false, -2.8f, 1.2f)
                quadToRelative(-1.1f, 1.2f, -1.2f, 3.6f)
            }
            path(
                fill = SolidColor(Color(0xFF309E3A)),
                strokeAlpha = 0.5f
            ) {
                moveToRelative(233f, 198.5f)
                lineToRelative(0.2f, -14f)
                horizontalLineToRelative(6f)
                quadToRelative(2.2f, 0f, 3.2f, 0.5f)
                quadToRelative(1f, 0.3f, 1.6f, 1.3f)
                curveToRelative(0.6f, 1f, 0.6f, 1.4f, 0.6f, 2.3f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = true, -1f, 2.6f)
                arcToRelative(5f, 5f, 0f, isMoreThanHalf = false, isPositiveArc = true, -2.7f, 1.2f)
                lineToRelative(1.5f, 1.2f)
                quadToRelative(0.6f, 0.6f, 1.5f, 2.3f)
                lineToRelative(1.7f, 2.8f)
                horizontalLineToRelative(-3.4f)
                lineToRelative(-2f, -3.2f)
                lineToRelative(-1.4f, -2f)
                lineToRelative(-0.9f, -0.6f)
                lineToRelative(-1.4f, -0.2f)
                horizontalLineToRelative(-0.6f)
                verticalLineToRelative(5.8f)
                close()
            }
            path(
                fill = SolidColor(Color.White),
                strokeAlpha = 0.5f
            ) {
                moveTo(236f, 190.5f)
                horizontalLineToRelative(2f)
                quadToRelative(2.1f, 0f, 2.6f, -0.2f)
                quadToRelative(0.5f, -0.1f, 0.8f, -0.5f)
                quadToRelative(0.4f, -0.6f, 0.3f, -1f)
                quadToRelative(0f, -0.9f, -0.4f, -1.2f)
                quadToRelative(-0.3f, -0.4f, -1f, -0.6f)
                horizontalLineToRelative(-2f)
                lineToRelative(-2.3f, -0.1f)
                close()
            }
            path(
                fill = SolidColor(Color(0xFF309E3A)),
                strokeAlpha = 0.5f
            ) {
                moveToRelative(249f, 185.2f)
                lineToRelative(5.2f, 0.3f)
                quadToRelative(1.7f, 0f, 2.6f, 0.3f)
                arcToRelative(5f, 5f, 0f, isMoreThanHalf = false, isPositiveArc = true, 2f, 1.4f)
                arcToRelative(6f, 6f, 0f, isMoreThanHalf = false, isPositiveArc = true, 1.2f, 2.4f)
                quadToRelative(0.4f, 1.4f, 0.3f, 3.3f)
                arcToRelative(9f, 9f, 0f, isMoreThanHalf = false, isPositiveArc = true, -0.5f, 3f)
                quadToRelative(-0.6f, 1.5f, -1.7f, 2.4f)
                arcToRelative(5f, 5f, 0f, isMoreThanHalf = false, isPositiveArc = true, -2f, 1f)
                quadToRelative(-1f, 0.3f, -2.5f, 0.2f)
                lineToRelative(-5.3f, -0.3f)
                close()
            }
            path(
                fill = SolidColor(Color.White),
                strokeAlpha = 0.5f
            ) {
                moveToRelative(251.7f, 187.7f)
                lineToRelative(-0.5f, 9.3f)
                horizontalLineToRelative(3.8f)
                quadToRelative(0.8f, 0f, 1.2f, -0.5f)
                quadToRelative(0.5f, -0.4f, 0.8f, -1.3f)
                reflectiveQuadToRelative(0.4f, -2.6f)
                lineToRelative(-0.1f, -2.5f)
                arcToRelative(3f, 3f, 0f, isMoreThanHalf = false, isPositiveArc = false, -0.8f, -1.4f)
                lineToRelative(-1.2f, -0.7f)
                lineToRelative(-2.3f, -0.3f)
                close()
            }
            path(
                fill = SolidColor(Color(0xFF309E3A)),
                strokeAlpha = 0.5f
            ) {
                moveToRelative(317.6f, 210.2f)
                lineToRelative(3.3f, -13.6f)
                lineToRelative(4.4f, 1f)
                lineToRelative(3.2f, 1f)
                quadToRelative(1.1f, 0.6f, 1.6f, 1.9f)
                reflectiveQuadToRelative(0.2f, 2.8f)
                quadToRelative(-0.3f, 1.2f, -1f, 2f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = true, -3f, 1.4f)
                quadToRelative(-1f, 0f, -3f, -0.5f)
                lineToRelative(-1.7f, -0.5f)
                lineToRelative(-1.2f, 5.2f)
                close()
            }
            path(
                fill = SolidColor(Color.White),
                strokeAlpha = 0.5f
            ) {
                moveToRelative(323f, 199.6f)
                lineToRelative(-0.8f, 3.8f)
                lineToRelative(1.5f, 0.4f)
                quadToRelative(1.6f, 0.4f, 2.2f, 0.3f)
                arcToRelative(2f, 2f, 0f, isMoreThanHalf = false, isPositiveArc = false, 1.6f, -1.5f)
                quadToRelative(0f, -0.7f, -0.2f, -1.3f)
                arcToRelative(2f, 2f, 0f, isMoreThanHalf = false, isPositiveArc = false, -1f, -0.9f)
                lineToRelative(-1.9f, -0.5f)
                lineToRelative(-1.3f, -0.3f)
                close()
            }
            path(
                fill = SolidColor(Color(0xFF309E3A)),
                strokeAlpha = 0.5f
            ) {
                moveToRelative(330.6f, 214.1f)
                lineToRelative(4.7f, -13.2f)
                lineToRelative(5.5f, 2f)
                quadToRelative(2.2f, 0.8f, 3f, 1.4f)
                quadToRelative(0.8f, 0.7f, 1f, 1.8f)
                curveToRelative(0.2f, 1.1f, 0.2f, 1.5f, 0f, 2.3f)
                quadToRelative(-0.6f, 1.5f, -1.8f, 2.2f)
                quadToRelative(-1.2f, 0.6f, -3f, 0.3f)
                quadToRelative(0.6f, 0.7f, 1f, 1.6f)
                lineToRelative(0.8f, 2.7f)
                lineToRelative(0.6f, 3.1f)
                lineToRelative(-3.1f, -1.1f)
                lineToRelative(-1f, -3.6f)
                lineToRelative(-0.7f, -2.4f)
                lineToRelative(-0.6f, -0.8f)
                quadToRelative(-0.3f, -0.4f, -1.3f, -0.7f)
                lineToRelative(-0.5f, -0.2f)
                lineToRelative(-2f, 5.6f)
                close()
            }
            path(
                fill = SolidColor(Color.White),
                strokeAlpha = 0.5f
            ) {
                moveToRelative(336f, 207.4f)
                lineToRelative(1.9f, 0.7f)
                quadToRelative(2f, 0.7f, 2.5f, 0.7f)
                reflectiveQuadToRelative(0.9f, -0.3f)
                quadToRelative(0.5f, -0.3f, 0.6f, -0.9f)
                quadToRelative(0.3f, -0.6f, 0f, -1.2f)
                lineToRelative(-0.8f, -0.9f)
                lineToRelative(-2f, -0.7f)
                lineToRelative(-2f, -0.7f)
                lineToRelative(-1.2f, 3.3f)
                close()
            }
            path(
                fill = SolidColor(Color(0xFF309E3A)),
                strokeAlpha = 0.5f
            ) {
                moveTo(347f, 213.6f)
                arcToRelative(9f, 9f, 0f, isMoreThanHalf = false, isPositiveArc = true, 1.7f, -3.2f)
                lineToRelative(1.8f, -1.5f)
                lineToRelative(2f, -0.7f)
                quadToRelative(1.5f, -0.1f, 3.1f, 0.4f)
                arcToRelative(7f, 7f, 0f, isMoreThanHalf = false, isPositiveArc = true, 4.2f, 3.3f)
                quadToRelative(1.2f, 2.4f, 0.2f, 5.7f)
                arcToRelative(7f, 7f, 0f, isMoreThanHalf = false, isPositiveArc = true, -3.4f, 4.5f)
                quadToRelative(-2.3f, 1.3f, -5.2f, 0.4f)
                arcToRelative(7f, 7f, 0f, isMoreThanHalf = false, isPositiveArc = true, -4.2f, -3.3f)
                arcToRelative(7f, 7f, 0f, isMoreThanHalf = false, isPositiveArc = true, -0.2f, -5.6f)
            }
            path(
                fill = SolidColor(Color.White),
                strokeAlpha = 0.5f
            ) {
                moveTo(349.8f, 214.4f)
                quadToRelative(-0.7f, 2.3f, 0f, 3.8f)
                curveToRelative(0.7f, 1.5f, 1.2f, 1.6f, 2.3f, 2f)
                quadToRelative(1.5f, 0.5f, 3f, -0.4f)
                quadToRelative(1.4f, -0.8f, 2.1f, -3.2f)
                quadToRelative(0.8f, -2.2f, 0f, -3.7f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = false, -2.2f, -2f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = false, -3f, 0.3f)
                quadToRelative(-1.5f, 0.8f, -2.2f, 3.2f)
            }
            path(
                fill = SolidColor(Color(0xFF309E3A)),
                strokeAlpha = 0.5f
            ) {
                moveToRelative(374.3f, 233.1f)
                lineToRelative(6.4f, -12.4f)
                lineToRelative(5.3f, 2.7f)
                arcToRelative(10f, 10f, 0f, isMoreThanHalf = false, isPositiveArc = true, 2.7f, 1.9f)
                quadToRelative(0.8f, 0.7f, 0.8f, 1.9f)
                curveToRelative(0f, 1.2f, 0f, 1.5f, -0.4f, 2.2f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = true, -2f, 2f)
                quadToRelative(-1.5f, 0.4f, -3.1f, -0.2f)
                quadToRelative(0.6f, 1f, 0.8f, 1.7f)
                quadToRelative(0.3f, 0.9f, 0.4f, 2.8f)
                lineToRelative(0.2f, 3.2f)
                lineToRelative(-3f, -1.5f)
                lineToRelative(-0.4f, -3.7f)
                lineToRelative(-0.3f, -2.5f)
                lineToRelative(-0.5f, -1f)
                lineToRelative(-1.2f, -0.7f)
                lineToRelative(-0.5f, -0.3f)
                lineToRelative(-2.7f, 5.2f)
                close()
            }
            path(
                fill = SolidColor(Color.White),
                strokeAlpha = 0.5f
            ) {
                moveToRelative(380.5f, 227.2f)
                lineToRelative(1.9f, 1f)
                quadToRelative(1.8f, 1f, 2.3f, 1f)
                reflectiveQuadToRelative(1f, -0.2f)
                quadToRelative(0.4f, -0.2f, 0.7f, -0.8f)
                reflectiveQuadToRelative(0.2f, -1.2f)
                lineToRelative(-0.7f, -1f)
                lineToRelative(-1.8f, -1f)
                lineToRelative(-2f, -1f)
                close()
            }
            path(
                fill = SolidColor(Color(0xFF309E3A)),
                strokeAlpha = 0.5f
            ) {
                moveTo(426.1f, 258.7f)
                arcToRelative(9f, 9f, 0f, isMoreThanHalf = false, isPositiveArc = true, 2.5f, -2.6f)
                arcToRelative(7f, 7f, 0f, isMoreThanHalf = false, isPositiveArc = true, 2.2f, -0.9f)
                arcToRelative(6f, 6f, 0f, isMoreThanHalf = false, isPositiveArc = true, 2.2f, 0f)
                quadToRelative(1.5f, 0.3f, 2.8f, 1.2f)
                arcToRelative(7f, 7f, 0f, isMoreThanHalf = false, isPositiveArc = true, 3f, 4.4f)
                quadToRelative(0.4f, 2.6f, -1.4f, 5.5f)
                arcToRelative(7f, 7f, 0f, isMoreThanHalf = false, isPositiveArc = true, -4.5f, 3.3f)
                arcToRelative(7f, 7f, 0f, isMoreThanHalf = false, isPositiveArc = true, -5.2f, -1.1f)
                arcToRelative(7f, 7f, 0f, isMoreThanHalf = false, isPositiveArc = true, -3f, -4.4f)
                quadToRelative(-0.4f, -2.7f, 1.4f, -5.4f)
            }
            path(
                fill = SolidColor(Color.White),
                strokeAlpha = 0.5f
            ) {
                moveTo(428.6f, 260.3f)
                quadToRelative(-1.4f, 2f, -1.1f, 3.6f)
                arcToRelative(4f, 4f, 0f, isMoreThanHalf = false, isPositiveArc = false, 1.6f, 2.5f)
                quadToRelative(1.5f, 1f, 3f, 0.6f)
                reflectiveQuadToRelative(2.9f, -2.4f)
                quadToRelative(1.4f, -2.1f, 1.1f, -3.6f)
                reflectiveQuadToRelative(-1.6f, -2.6f)
                curveToRelative(-1.4f, -1.1f, -2f, -0.8f, -3f, -0.5f)
                quadToRelative(-1.5f, 0.3f, -3f, 2.4f)
                close()
            }
            path(fill = SolidColor(Color(0xFF309E3A))) {
                moveToRelative(301.8f, 204.5f)
                lineToRelative(2.3f, -9.8f)
                lineToRelative(7.2f, 1.7f)
                lineToRelative(-0.3f, 1.6f)
                lineToRelative(-5.3f, -1.2f)
                lineToRelative(-0.5f, 2.2f)
                lineToRelative(4.9f, 1.1f)
                lineToRelative(-0.4f, 1.7f)
                lineToRelative(-4.9f, -1.2f)
                lineToRelative(-0.6f, 2.7f)
                lineToRelative(5.5f, 1.3f)
                lineToRelative(-0.4f, 1.6f)
                close()
            }
        }.build()

        return _FlagBr!!
    }

@Suppress("ObjectPropertyName")
private var _FlagBr: ImageVector? = null


