/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EpubReader: typeof import('./src/components/EpubReader.vue')['default']
    IconFormatLineSpacingDown: typeof import('./src/components/IconFormatLineSpacingDown.vue')['default']
    SettingsSelect: typeof import('./src/components/SettingsSelect.vue')['default']
    SettingsSwitch: typeof import('./src/components/SettingsSwitch.vue')['default']
    ShortcutHelpDialog: typeof import('./src/components/ShortcutHelpDialog.vue')['default']
    TocList: typeof import('./src/components/TocList.vue')['default']
    TocListItem: typeof import('./src/components/TocListItem.vue')['default']
  }
}
