package io.github.snd_r.komelia.strings

val EnStrings = Strings(
    seriesFilter = SeriesFilterStrings(
        resetFilters = "Reset filters",
        hideFilters = "Hide filters",
        anyValue = "Any",
        search = "Search",

        sort = "Sort by",
        sortTitleAsc = "Title Ascending",
        sortTitleDesc = "Title Descending",
        sortDateAddedAsc = "Oldest Added",
        sortDateAddedDesc = "Recently Added",
        sortReleaseDateAsc = "Oldest Release Date",
        sortReleaseDateDesc = "Latest Release Date",
        sortUpdatedAsc = "Oldest Update",
        sortUpdatedDesc = "Latest Update",
        sortFolderNameAsc = "Folder Name Ascending",
        sortFolderNameDesc = "Folder Name Descending",
        sortBooksCountAsc = "Least Books",
        sortBooksCountDesc = "Most Books",

        filterTags = "Filter tags",
        filterTagsSearch = "Search tags",
        filterTagsReset = "Reset",
        filterTagsGenreLabel = "Genre",
        filterTagsTagsLabel = "Tags",
        filterTagsShowMore = "Show more",
        filterTagsShowLess = "Show less",

        readStatus = "Read status",
        readStatusUnread = "Unread",
        readStatusInProgress = "In progress",
        readStatusRead = "Read",

        publicationStatus = "Publication status",
        pubStatusEnded = "Ended",
        pubStatusOngoing = "Ongoing",
        pubStatusAbandoned = "Abandoned",
        pubStatusHiatus = "Hiatus",

        complete = "Complete",
        oneshot = "Oneshot",
        authors = "Authors",
        publisher = "Publisher",
        language = "Language",
        releaseDate = "Release date",
        ageRating = "Age rating"
    ),
    seriesEdit = SeriesEditStrings(
        title = "Title",
        sortTitle = "Sort title",
        summary = "Summary",
        language = "Language",

        status = "Status",
        statusEnded = "Ended",
        statusOngoing = "Ongoing",
        statusAbandoned = "Abandoned",
        statusHiatus = "Hiatus",

        readingDirection = "Reading Direction",
        readingDirectionLeftToRight = "Left to right",
        readingDirectionRightToLeft = "Right to left",
        readingDirectionVertical = "Vertical",
        readingDirectionWebtoon = "Webtoon",
        publisher = "Publisher",
        ageRating = "Age rating",
        totalBookCount = "Total book count"
    ),
    libraryEdit = LibraryEditStrings(
        emptyTrashAfterScan = "Empty trash automatically after every scan",
        scanForceModifiedTime = "Force directory modified time",
        scanOnStartup = "Scan on startup",
        oneshotsDirectory = "One-Shots directory",
        excludeDirectories = "Directory exclusions",

        scanInterval = "Scan interval",
        scanIntervalDisabled = "Disabled",
        scanIntervalHourly = "Hourly",
        scanIntervalEvery6H = "Every 6 hours",
        scanIntervalEvery12H = "Every 12 hours",
        scanIntervalDaily = "Daily",
        scanIntervalWeekly = "Weekly",

        hashFiles = "Compute hash for files",
        hashPages = "Compute hash for pages",
        analyzeDimensions = "Analyze pages dimensions",
        repairExtensions = "Automatically repair incorrect file extensions",
        convertToCbz = "Automatically convert to CBZ",
        seriesCover = "Series cover",
        coverFirst = "First",
        coverFirstUnreadOrFirst = "First unread else first",
        coverFirstUnreadOrLast = "First unread else last",
        coverLast = "Last"
    ),
    userEdit = UserEditStrings(
        contentRestrictions = "Content restrictions",
        age = "Age",
        labelsAllow = "Allow only labels",
        labelsExclude = "Exclude labels",
        ageRestriction = "Age restrictions",
        ageRestrictionNone = "No restriction",
        ageRestrictionAllowOnly = "Allow only under",
        ageRestrictionExclude = "Exclude over"
    ),
    readerSettings = ReaderSettingsStrings(
        scaleType = "Scale type",
        scaleScreen = "Screen",
        scaleFitWidth = "Fit width",
        scaleFitHeight = "Fit height",
        scaleOriginal = "Original",
        upsample = "Upsample on zoom",
        readingDirection = "Reading direction",
        readingDirectionLeftToRight = "Left to right",
        readingDirectionRightToLeft = "Right to left",
        layout = "Page layout",
        layoutSinglePage = "Single page",
        layoutDoublePages = "Double pages",
        offsetPages = "Offset pages",
        decoder = "Image Decoder/Sampler",
        pageNumber = "page",
        memoryUsage = "Memory usage",
        pageScaledSize = "scaled size",
        pageOriginalSize = "original size",
        noPageDimensionsWarning = "Original page dimensions are not calculated. Scaling might not work as intended"
    ),
    settings = SettingsStrings(
        serverSettings = "Server Settings",
        thumbnailSize = "Thumbnail size",
        thumbnailSizeDefault = "Default (300px)",
        thumbnailSizeMedium = "Medium (600px)",
        thumbnailSizeLarge = "Large (900px)",
        thumbnailSizeXLarge = "X-Large (1200px)",

        thumbnailRegenTitle = "Regenerate thumbnails",
        thumbnailRegenBody = "Thumbnails size has changed. Do you want to regenerate book thumbnails?",
        thumbnailRegenIfBigger = "YES, BUT ONLY IF BIGGER",
        thumbnailRegenAllBooks = "YES, ALL BOOKS",
        thumbnailRegenNo = "NO",

        deleteEmptyCollections = "Delete empty collections after scan",
        deleteEmptyReadLists = "Delete empty read lists after scan",
        taskPoolSize = "Task threads",
        rememberMeDurationDays = "Remember me duration (in days)",
        renewRememberMeKey = "Regenerate RememberMe key",
        serverPort = "Server port",
        serverContextPath = "Base URL",
        requiresRestart = "Requires restart to take effect",
        serverSettingsDiscard = "Discard",
        serverSettingsSave = "Save Changes",

        imageCardSize = "Image card size",
        decoder = "Image Decoder/Sampler"
    )
)