include(ExternalProject)

ExternalProject_Add(ep_fftw
    URL https://www.fftw.org/fftw-3.3.10.tar.gz
    CMAKE_ARGS
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/fakeroot
        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
        -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
        -DCMAKE_FIND_ROOT_PATH=${CMAKE_FIND_ROOT_PATH}
        -DANDROID_ABI=${ANDROID_ABI}
        -DANDROID_PLATFORM=${ANDROID_PLATFORM}
        -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=OFF
        -DCMAKE_POLICY_DEFAULT_CMP0057:STRING=NEW
    DEPENDS ep_zlib
    USES_TERMINAL_DOWNLOAD true
    USES_TERMINAL_BUILD true
)