include(ExternalProject)

ExternalProject_Add(ep_jxl
    GIT_REPOSITORY      https://github.com/libjxl/libjxl
    GIT_TAG             v0.10.3
    DEPENDS ep_highway ep_brotli
    CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/fakeroot
        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
        -DANDROID_ABI=${ANDROID_ABI}
        -DANDROID_PLATFORM=${ANDROID_PLATFORM}
        -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=OFF
        -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
        -DCMAKE_FIND_ROOT_PATH=${CMAKE_FIND_ROOT_PATH}
        -DJPEGXL_ENABLE_JPEGLI=false
        #-DJPEGXL_ENABLE_JPEGLI_LIBJPEG=true
        #-DJPEGXL_INSTALL_JPEGLI_LIBJPEG=true
        #-DJPEGXL_FORCE_SYSTEM_HWY=true
        #-DJPEGXL_FORCE_SYSTEM_BROTLI=true
        -DJPEGXL_ENABLE_OPENEXR=false
        -DJPEGXL_ENABLE_TOOLS=false
        -DJPEGXL_BUNDLE_LIBPNG=false
        -DJPEGXL_ENABLE_JNI=false
        -DJPEGXL_ENABLE_SJPEG=false
        -DBUILD_TESTING=false
    USES_TERMINAL_DOWNLOAD true
    USES_TERMINAL_BUILD true
)